/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd_ef;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author Lorrain
 */
public class Interfaz extends javax.swing.JFrame {

    private DefaultListModel inicializarJList;
    private int numeroDeProceso;
    private int numeroDeMensaje = 1;
    private int[] relojLogico= {0,0,0,0,0,0};
    private int puertoEnvia;
    private int puerto;
    private String direccionIP;
    private String textoMensaje;
    private ArrayList<Mensaje> mensajesEspera = new ArrayList();
    private ArrayList<Mensaje> mensajesEntregado = new ArrayList();
    private ArrayList<Mensaje> mensajesCreado = new ArrayList();
    private ArrayList<Integer> CI = new ArrayList();
    
    
    

    public int getNumeroDeProceso() {
        return numeroDeProceso;
    }

    public void setNumeroDeProceso(int numeroDeProceso) {
        this.numeroDeProceso = numeroDeProceso;
    }

    public int getPuerto() {
        return puerto;
    }

    public void setPuerto(int puerto) {
        this.puerto = puerto;
    }
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        inicializarJList = new DefaultListModel();
        this.idProceso.setText(Integer.toString(numeroDeProceso));

    }

    public void setIdProceso(int perro) {
        this.idProceso.setText(Integer.toString(perro));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        esperaTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        entregadosTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        creadosList = new javax.swing.JList<String>();
        jLabel3 = new javax.swing.JLabel();
        textoMensajeTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        relojLogicoTA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CITA = new javax.swing.JTextArea();
        bCrear = new javax.swing.JButton();
        proceso1 = new javax.swing.JButton();
        proceso2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        proceso3 = new javax.swing.JButton();
        proceso4 = new javax.swing.JButton();
        proceso5 = new javax.swing.JButton();
        proceso6 = new javax.swing.JButton();
        numeroProceso = new javax.swing.JLabel();
        idProceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        esperaTA.setColumns(20);
        esperaTA.setRows(5);
        jScrollPane1.setViewportView(esperaTA);

        entregadosTA.setColumns(20);
        entregadosTA.setRows(5);
        jScrollPane2.setViewportView(entregadosTA);

        jLabel1.setText("Mensajes en espera");

        jLabel2.setText("Mensajes entregados");

        jScrollPane3.setViewportView(creadosList);

        jLabel3.setText("Mensajes creados");

        jLabel4.setText("Crear mensaje");

        relojLogicoTA.setColumns(20);
        relojLogicoTA.setRows(5);
        jScrollPane4.setViewportView(relojLogicoTA);

        jLabel5.setText("Reloj Logico");

        jLabel6.setText("CI");

        CITA.setColumns(20);
        CITA.setRows(5);
        jScrollPane5.setViewportView(CITA);

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        proceso1.setText("Proceso 1");
        proceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso1ActionPerformed(evt);
            }
        });

        proceso2.setText("Proceso 2");
        proceso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Procesos");

        proceso3.setText("Proceso 3");
        proceso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso3ActionPerformed(evt);
            }
        });

        proceso4.setText("Proceso 4");
        proceso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso4ActionPerformed(evt);
            }
        });

        proceso5.setText("Proceso 5");
        proceso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso5ActionPerformed(evt);
            }
        });

        proceso6.setText("Proceso 6");
        proceso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso6ActionPerformed(evt);
            }
        });

        numeroProceso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroProceso.setText("Numero Proceso");

        idProceso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idProceso.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel5))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(148, 148, 148)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(textoMensajeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(bCrear)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(proceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(proceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(proceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(proceso5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(proceso6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(numeroProceso)
                                .addGap(26, 26, 26)
                                .addComponent(idProceso)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroProceso)
                    .addComponent(idProceso))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoMensajeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bCrear))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceso1)
                    .addComponent(proceso3)
                    .addComponent(proceso2)
                    .addComponent(proceso4)
                    .addComponent(proceso5)
                    .addComponent(proceso6))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void proceso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso2ActionPerformed
        // TODO add your handling code here:
        direccionIP = "192.168.1.244";
        puertoEnvia = 20002;        
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso2ActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:
        textoMensaje = textoMensajeTF.getText();
        numeroDeProceso = Integer.parseInt(idProceso.getText());
        Mensaje m = new Mensaje(textoMensaje, numeroDeProceso, numeroDeMensaje, CI);        
        //System.out.println("Mensaje Creado: " + numeroDeProceso + " " + numeroDeMensaje + " " + textoMensaje);
        numeroDeMensaje++;
        inicializarJList.addElement(m.toString());
        creadosList.setModel(inicializarJList);
        relojLogico[numeroDeProceso-1] ++;
        CI.clear();
        imprimirCI(CI);
        

        
        //System.out.println(puerto + " " + numeroDeProceso);
        
        
    }//GEN-LAST:event_bCrearActionPerformed

    private void proceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso1ActionPerformed
        // TODO add your handling code here:
        direccionIP = "192.168.1.83";
        puertoEnvia = 20001;
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso1ActionPerformed

    private void proceso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso5ActionPerformed
        // TODO add your handling code here:
        direccionIP = "localhost";
        puertoEnvia = 20005;
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso5ActionPerformed

    private void proceso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso3ActionPerformed
        // TODO add your handling code here:
        direccionIP = "localhost";
        puertoEnvia = 20003;
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso3ActionPerformed

    private void proceso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso4ActionPerformed
        // TODO add your handling code here:
        direccionIP = "localhost";
        puertoEnvia = 20004;
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso4ActionPerformed

    private void proceso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso6ActionPerformed
        // TODO add your handling code here:
        direccionIP = "localhost";
        puertoEnvia = 20006;
        Enviar(creadosList.getSelectedValue());
    }//GEN-LAST:event_proceso6ActionPerformed
public void Enviar(String mensaje){
    Comunicacion comunicar = new Comunicacion(mensaje);
    comunicar.Enviar(direccionIP, puertoEnvia);
}
public void imprimirCI(ArrayList<Integer> ci) {
    String c = "";
        if (ci.isEmpty()) {
            CITA.append("0");
            CITA.append(System.getProperty("line.separator"));
        }
        for (int i = 0; i < ci.size(); i++) {
            c = c + "," + ci.get(i);
        }

        CITA.append(c);
        CITA.append(System.getProperty("line.separator"));
}
public void Recibir(){
    Comunicacion comunicar2 = new Comunicacion();
    comunicar2.Recibir(puerto);
    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CITA;
    private javax.swing.JButton bCrear;
    private javax.swing.JList<String> creadosList;
    private javax.swing.JTextArea entregadosTA;
    private javax.swing.JTextArea esperaTA;
    private javax.swing.JLabel idProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel numeroProceso;
    private javax.swing.JButton proceso1;
    private javax.swing.JButton proceso2;
    private javax.swing.JButton proceso3;
    private javax.swing.JButton proceso4;
    private javax.swing.JButton proceso5;
    private javax.swing.JButton proceso6;
    private javax.swing.JTextArea relojLogicoTA;
    private javax.swing.JTextField textoMensajeTF;
    // End of variables declaration//GEN-END:variables
}
